### PR TITLE
DO NOT MERGE: Update avro schemas

### PR DESCRIPTION
**Pull request by moltude**
Moved Avro schema files into separate files
Updated schemas and namespace to match specs

### CODE REVIEW

**Comment by moltude** [comment]
Bumping for follow-up at sprint review/planning. @markbreedlove Just need to confirm whether there was any additional work required before opening this up for review.

**Comment by markbreedlove** [comment]
I've just realized that EdmPlace should no longer be named as such. We should name this DplaPlace, because I changed it to be DplaPlace from the MAP3.1 schema. `edm:Place` is a specific thing that this is not.

**Comment by mdellabitta** [comment]
Good to know!

**Comment by markbreedlove** [comment]
Actually, it's OK in this PR ... I made this comment in the wrong PR.

**Comment by markbreedlove** [comment]
@moltude: Thanks for your commit to assign the Avro schemas from their files, instead of having them hardcoded.  I will close this PR and squash the branch so that @AudreyAltman can work with it for https://digitalpubliclibraryofamerica.atlassian.net/browse/DT-1478 .

I don't understand the reason for the `println` statements in OaiHarvesterMain -- are they for debugging? -- but they are no issue within the context of this change, which is simply to change the source of the schema string.

**Pull request closed without merging**
