### PR TITLE
Fix/mdl mapping

### PR DESCRIPTION
**Pull request by moltude**
* Mapping error no longer include full stacktrace
* A number of initial mapping fixes for MDL 
* extractStrings() in JsonExtractionUtils now returns unique values
* Add iterify() method to JsonExtractionUtils to ensure that all JValues are wrapped in a JArray
* Add collection.description and language.iso_639_3 properties to JSON-L export

### CODE REVIEW

**Comment by mdellabitta** [comment]
To be honest, I'm a little concerned by "extractStrings() in JsonExtractionUtils now returns unique values" because it removes the possibility of getting two lists of strings and cross referencing them with one another. Some of the `distinct` stuff is being handled by Audrey's PR, is that a better place to handle that?

**Comment by AudreyAltman** [comment]
FWIW the standard enrichment I wrote is intentionally very thorough, so it should be ok to bypass it here, unless there’s a specific reason we need it at mapping.

**Comment by AudreyAltman** [comment]
I have no concerns to add to @mdellabitta’s so I will approve. Thanks @scott!

**Comment by moltude** [comment]
I'll remove

**Pull request merged**
