### PR TITLE
Fixup wiki markup to comply with CC licenses and permissions

### PR DESCRIPTION
**Pull request by moltude**

### CODE REVIEW

**Review by mdellabitta — APPROVED** [review]
Just thinking out loud: if the wikitext generation gets more complicated, we might want to use a templating language like https://www.playframework.com/documentation/2.2.x/ScalaTemplates or https://velocity.apache.org/

**Comment by moltude** [comment]
@mdellabitta that would a good tool to throw in the mix

**Comment by moltude** [comment]
I'm going to hold on merging this PR until @DominicBM has a chance to sign off on the revised wiki markup

**Review by DominicBM — APPROVED** [review]
Output looks good, based on the documentation! I’m actually hoping the complexity decreased over time. Once we are providing structured data, we need to worry less about formatted text.

**Pull request merged**
