### PR TITLE
Addresses IN-586 Updates to DPLA model

### PR DESCRIPTION
**Pull request by moltude**
- Add isReferencedBy field to EdmWebResource
- Update model and row converters with new field
- Update ModelConverterTest

### CODE REVIEW

**Comment by moltude** [comment]
No problem to test, Ohio is enriching now but since its in mid-process the `row > model` pieces is working ;)

**Comment by mdellabitta** [comment]
Just want to make sure we know ahead of time if we need to reprocess all the data prior to merging this.

**Comment by moltude** [comment]
@mdellabitta Now works. Enriches older version of mapped data. Took more fiddling that I expected.

**Comment by mdellabitta** [comment]
Nice, that looks super tidy!

**Pull request merged**
